---
title: "final entrega 2"
author: "Camila"
date: "2025-11-22"
output: html_document
---
```{r}
library(rio)
library(dplyr)
```
```{r}
dataPerú=import("PER_2021_LAPOP_AmericasBarometer_v1.2_w (1).dta")
```
```{r}
dataPerú$idnum=NULL
dataPerú$uniq_id=NULL
dataPerú$year=NULL
dataPerú$wave=NULL
dataPerú$estratopri=NULL
dataPerú$nationality=NULL
dataPerú$strata=NULL
dataPerú$upm=NULL
dataPerú$prov1t=NULL
```
```{r}
dataPerú$psc11n=NULL
dataPerú$psc11an=NULL
dataPerú$psc15=NULL
dataPerú$psc16=NULL
dataPerú$psc13n_1=NULL
dataPerú$psc13n_2=NULL
dataPerú$psc13n_3=NULL
dataPerú$psc13n_4=NULL
dataPerú$psc13n_5=NULL
dataPerú$psc13n_7=NULL
dataPerú$psc13n_11=NULL
dataPerú$psc13n_12=NULL
dataPerú$psc13n_13=NULL
dataPerú$psc13n_77=NULL
dataPerú$idiomaq=NULL
dataPerú$formatq=NULL
dataPerú$sexi=NULL
dataPerú$srvyrid=NULL
dataPerú$fecha=NULL
dataPerú$conocim=NULL
```

```{r}
dataPerú$psc2c2_1=NULL
dataPerú$psc2c2_2=NULL
dataPerú$psc2c2_3=NULL
dataPerú$psc2c2_4=NULL
dataPerú$psc2c2_5=NULL
dataPerú$psc2c2_6=NULL
dataPerú$psc2c2_7=NULL
dataPerú$psc2c2_8=NULL
dataPerú$psc2c2_9=NULL
dataPerú$psc2c2_10=NULL
dataPerú$psc2c2_11=NULL
dataPerú$psc2c2_12=NULL
dataPerú$psc2c2_13=NULL
dataPerú$psc2c2_14=NULL
dataPerú$psc2c2_15=NULL
dataPerú$psc2c2_16=NULL
dataPerú$psc2c2_17=NULL
dataPerú$psc2c2_18=NULL
dataPerú$psc2c2_19=NULL
dataPerú$psc2c2_77=NULL
dataPerú$psc2f1=NULL
dataPerú$psc2f2_1=NULL
dataPerú$psc2f2_2=NULL
dataPerú$psc2f2_3=NULL
dataPerú$psc2f2_4=NULL
dataPerú$psc2f2_5=NULL
dataPerú$psc2f2_6=NULL
dataPerú$psc2f2_7=NULL
dataPerú$psc2f2_8=NULL
dataPerú$psc2f2_9=NULL
dataPerú$psc2f2_10=NULL
dataPerú$psc2f2_11=NULL
dataPerú$psc2f2_12=NULL
dataPerú$psc2f2_13=NULL
dataPerú$psc2f2_14=NULL
dataPerú$psc2f2_15=NULL
dataPerú$psc2f2_16=NULL
dataPerú$psc2f2_17=NULL
dataPerú$psc2f2_18=NULL
dataPerú$psc2f2_19=NULL
dataPerú$psc2f2_77=NULL
dataPerú$psc2f3=NULL
dataPerú$psc2f4_1=NULL
dataPerú$psc2f4_2=NULL
dataPerú$psc2f4_3=NULL
dataPerú$psc2f4_77=NULL
dataPerú$psc7n=NULL
dataPerú$psc8n=NULL
dataPerú$psc9n=NULL
dataPerú$psc14=NULL
dataPerú$psc12n=NULL
```

```{r}
dataPerú$covidedu1_4=NULL
dataPerú$covidedu1_5=NULL
dataPerú$covidedu2=NULL
dataPerú$etid=NULL
dataPerú$gi0n=NULL
dataPerú$r3=NULL
dataPerú$r4=NULL
dataPerú$r6=NULL
dataPerú$r7=NULL
dataPerú$r15=NULL
dataPerú$r18n=NULL
dataPerú$r18=NULL
dataPerú$r16=NULL
dataPerú$r27=NULL
dataPerú$psc1n=NULL
dataPerú$psc1c1=NULL
dataPerú$psc1c2_1=NULL
dataPerú$psc1c2_2=NULL
dataPerú$psc1c2_3=NULL
dataPerú$psc1c2_4=NULL
dataPerú$psc1c2_5=NULL
dataPerú$psc1c2_6=NULL
dataPerú$psc1c2_7=NULL
dataPerú$psc1c2_8=NULL
dataPerú$psc1c2_9=NULL
dataPerú$psc1c2_10=NULL
dataPerú$psc1c2_11=NULL
dataPerú$psc1c2_12=NULL
dataPerú$psc1c2_13=NULL
dataPerú$psc1c2_14=NULL
dataPerú$psc1c2_15=NULL
dataPerú$psc1c2_16=NULL
dataPerú$psc1c2_17=NULL
dataPerú$psc1c2_18=NULL
dataPerú$psc1c2_19=NULL
dataPerú$psc1c2_77=NULL
dataPerú$psc1c3=NULL
dataPerú$psc1t1_1=NULL
dataPerú$psc1t1_2=NULL
dataPerú$psc1t1_3=NULL
dataPerú$psc1t1_4=NULL
dataPerú$psc1t1_5=NULL
dataPerú$psc1t1_6=NULL
dataPerú$psc1t1_77=NULL
dataPerú$psc1c4=NULL
dataPerú$psc1t2_1=NULL
dataPerú$psc1t2_2=NULL
dataPerú$psc1t2_2=NULL
dataPerú$psc1t2_3=NULL
dataPerú$psc1t2_4=NULL
dataPerú$psc1t2_5=NULL
dataPerú$psc1t2_6=NULL
dataPerú$psc1t2_7=NULL
dataPerú$psc1t2_8=NULL
dataPerú$psc1t2_9=NULL
dataPerú$psc1t2_10=NULL
dataPerú$psc1t2_11=NULL
dataPerú$psc1t2_12=NULL
dataPerú$psc1t2_13=NULL
dataPerú$psc1t2_14=NULL
dataPerú$psc1t2_15=NULL
dataPerú$psc1t2_16=NULL
dataPerú$psc1t2_17=NULL
dataPerú$psc1t2_18=NULL
dataPerú$psc1t2_19=NULL
dataPerú$psc1t2_77=NULL
dataPerú$psc1t3=NULL
dataPerú$psc1t4=NULL
dataPerú$psc2n=NULL
dataPerú$psc2r1=NULL
dataPerú$psc2r2_1=NULL
dataPerú$psc2r2_2=NULL
dataPerú$psc2r2_3=NULL
dataPerú$psc2r2_4=NULL
dataPerú$psc2r2_5=NULL
dataPerú$psc2r2_6=NULL
dataPerú$psc2r2_7=NULL
dataPerú$psc2r2_8=NULL
dataPerú$psc2r2_9=NULL
dataPerú$psc2r2_10=NULL
dataPerú$psc2r2_11=NULL
dataPerú$psc2r2_12=NULL
dataPerú$psc2r2_13=NULL
dataPerú$psc2r2_14=NULL
dataPerú$psc2r2_15=NULL
dataPerú$psc2r2_16=NULL
dataPerú$psc2r2_17=NULL
dataPerú$psc2r2_18=NULL
dataPerú$psc2r2_19=NULL
dataPerú$psc2r2_99=NULL
dataPerú$psc2r2_77=NULL
dataPerú$psc2c1=NULL
```

```{r}
dataPerú$jc13covid=NULL
dataPerú$jc15a=NULL
dataPerú$jccov1=NULL
dataPerú$jccov2=NULL
dataPerú$vic1ext=NULL
dataPerú$aoj11=NULL
dataPerú$countfair1=NULL
dataPerú$countfair2=NULL
dataPerú$countfair2=NULL
dataPerú$countfair3=NULL
dataPerú$countfair4=NULL
dataPerú$wvsi3=NULL
dataPerú$chm1bn=NULL
dataPerú$chm2bn=NULL
dataPerú$cses6n=NULL
dataPerú$b0t=NULL
dataPerú$b2=NULL
dataPerú$b3=NULL
dataPerú$b4=NULL
dataPerú$b12=NULL
dataPerú$b13=NULL
dataPerú$b18=NULL
dataPerú$b21=NULL
dataPerú$b32=NULL
dataPerú$b37=NULL
dataPerú$b47a=NULL
dataPerú$dst1bn=NULL
dataPerú$pr3dnr=NULL
```

```{r}
dataPerú$pr3enr=NULL
dataPerú$drk1c=NULL
dataPerú$drk1n=NULL
dataPerú$drr1=NULL
dataPerú$drr1a=NULL
dataPerú$drr1b=NULL
dataPerú$env1calt=NULL
dataPerú$envp41=NULL
dataPerú$envp42=NULL
dataPerú$m1=NULL
dataPerú$ing4=NULL
dataPerú$exc2=NULL
dataPerú$genor2=NULL
dataPerú$genor4=NULL
dataPerú$aojg2n=NULL
dataPerú$aojg3n1=NULL
dataPerú$mil10a=NULL
dataPerú$mil10e=NULL
dataPerú$ccch1=NULL
dataPerú$ccch3=NULL
dataPerú$ccch4=NULL
dataPerú$ccch6=NULL
dataPerú$ccus1=NULL
dataPerú$ccus3=NULL
dataPerú$ccus4=NULL
dataPerú$ccus6=NULL
dataPerú$ie1=NULL
dataPerú$ie2=NULL
dataPerú$edr=NULL
dataPerú$ocup4a=NULL
dataPerú$ocup4a=NULL
dataPerú$q10newt=NULL
dataPerú$q11n=NULL
dataPerú$q12c=NULL
dataPerú$q12bn=NULL
dataPerú$covidedu1_1=NULL
dataPerú$covidedu1_2=NULL
dataPerú$covidedu1_3=NULL
```

```{r}
dataPerú$covidedu1_4=NULL
dataPerú$covidedu1_5=NULL
dataPerú$covidedu2=NULL
dataPerú$etid=NULL
dataPerú$gi0n=NULL
dataPerú$r3=NULL
dataPerú$r4=NULL
dataPerú$r6=NULL
dataPerú$r7=NULL
dataPerú$r15=NULL
dataPerú$r18n=NULL
dataPerú$r18=NULL
dataPerú$r16=NULL
dataPerú$r27=NULL
dataPerú$psc1n=NULL
dataPerú$psc1c1=NULL
dataPerú$psc1c2_1=NULL
dataPerú$psc1c2_2=NULL
dataPerú$psc1c2_3=NULL
dataPerú$psc1c2_4=NULL
dataPerú$psc1c2_5=NULL
dataPerú$psc1c2_6=NULL
dataPerú$psc1c2_7=NULL
dataPerú$psc1c2_8=NULL
dataPerú$psc1c2_9=NULL
dataPerú$psc1c2_10=NULL
dataPerú$psc1c2_11=NULL
dataPerú$psc1c2_12=NULL
dataPerú$psc1c2_13=NULL
dataPerú$psc1c2_14=NULL
dataPerú$psc1c2_15=NULL
dataPerú$psc1c2_16=NULL
dataPerú$psc1c2_17=NULL
dataPerú$psc1c2_18=NULL
dataPerú$psc1c2_19=NULL
dataPerú$psc1c2_77=NULL
dataPerú$psc1c3=NULL
dataPerú$psc1t1_1=NULL
dataPerú$psc1t1_2=NULL
dataPerú$psc1t1_3=NULL
dataPerú$psc1t1_4=NULL
dataPerú$psc1t1_5=NULL
dataPerú$psc1t1_6=NULL
dataPerú$psc1t1_77=NULL
dataPerú$psc1c4=NULL
dataPerú$psc1t2_1=NULL
dataPerú$psc1t2_2=NULL
dataPerú$psc1t2_2=NULL
dataPerú$psc1t2_3=NULL
dataPerú$psc1t2_4=NULL
dataPerú$psc1t2_5=NULL
dataPerú$psc1t2_6=NULL
dataPerú$psc1t2_7=NULL
dataPerú$psc1t2_8=NULL
dataPerú$psc1t2_9=NULL
dataPerú$psc1t2_10=NULL
dataPerú$psc1t2_11=NULL
dataPerú$psc1t2_12=NULL
dataPerú$psc1t2_13=NULL
dataPerú$psc1t2_14=NULL
dataPerú$psc1t2_15=NULL
dataPerú$psc1t2_16=NULL
dataPerú$psc1t2_17=NULL
dataPerú$psc1t2_18=NULL
dataPerú$psc1t2_19=NULL
dataPerú$psc1t2_77=NULL
dataPerú$psc1t3=NULL
dataPerú$psc1t4=NULL
dataPerú$psc2n=NULL
dataPerú$psc2r1=NULL
dataPerú$psc2r2_1=NULL
dataPerú$psc2r2_2=NULL
dataPerú$psc2r2_3=NULL
dataPerú$psc2r2_4=NULL
dataPerú$psc2r2_5=NULL
dataPerú$psc2r2_6=NULL
dataPerú$psc2r2_7=NULL
dataPerú$psc2r2_8=NULL
dataPerú$psc2r2_9=NULL
dataPerú$psc2r2_10=NULL
dataPerú$psc2r2_11=NULL
dataPerú$psc2r2_12=NULL
dataPerú$psc2r2_13=NULL
dataPerú$psc2r2_14=NULL
dataPerú$psc2r2_15=NULL
dataPerú$psc2r2_16=NULL
dataPerú$psc2r2_17=NULL
dataPerú$psc2r2_18=NULL
dataPerú$psc2r2_19=NULL
dataPerú$psc2r2_99=NULL
dataPerú$psc2r2_77=NULL
dataPerú$psc2c1=NULL
```
```{r}
dataPerú$ur1new=NULL
dataPerú$q1tb=NULL
dataPerú$q2=NULL
dataPerú$wt=NULL
dataPerú$weight1500=NULL
dataPerú$core_a_core_b=NULL
dataPerú$perprov1t=NULL
dataPerú$perdistrito1t=NULL
dataPerú$covid2at=NULL
dataPerú$idio2=NULL
dataPerú$idio2cov=NULL
dataPerú$a4=NULL
```
```{r}
dataPerú$fs2=NULL
dataPerú$fs2covidn=NULL
dataPerú$covid11n=NULL
dataPerú$it1=NULL
dataPerú$jc13=NULL
dataPerú$exc7=NULL
```
```{r}
names(dataPerú)
```
cambiar de nombre a las variables 
```{r}
library(tidyverse)
```
```{r}
names(dataPerú) = c("Perú", "ParticipaciónP", "RespetoP", "ConfianzaP", "ToleranciaP", "TransparenciaP", "PercepciónP")
names(dataPerú)
```

```{r}
dataUruguay=import("URY_2021_LAPOP_AmericasBarometer_v1.2_w.dta")
```
limpieza
```{r}
dataUruguay$fs2=NULL
dataUruguay$fs2covidn=NULL
dataUruguay$covid11n=NULL
dataUruguay$it1=NULL
dataUruguay$jc13=NULL
```
```{r}
dataUruguay$ur1new=NULL
dataUruguay$q1tb=NULL
dataUruguay$q2=NULL
dataUruguay$wt=NULL
dataUruguay$weight1500=NULL
dataUruguay$core_a_core_b=NULL
dataUruguay$perprov1t=NULL
dataUruguay$perdistrito1t=NULL
dataUruguay$covid2at=NULL
dataUruguay$idio2=NULL
dataUruguay$idio2cov=NULL
dataUruguay$a4=NULL
```
```{r}
dataUruguay$covidedu1_4=NULL
dataUruguay$covidedu1_5=NULL
dataUruguay$covidedu2=NULL
dataUruguay$etid=NULL
dataUruguay$gi0n=NULL
dataUruguay$r3=NULL
dataUruguay$r4=NULL
dataUruguay$r6=NULL
dataUruguay$r7=NULL
dataUruguay$r15=NULL
dataUruguay$r18n=NULL
dataUruguay$r18=NULL
dataUruguay$r16=NULL
dataUruguay$r27=NULL
dataUruguay$psc1n=NULL
dataUruguay$psc1c1=NULL
dataUruguay$psc1c2_1=NULL
dataUruguay$psc1c2_2=NULL
dataUruguay$psc1c2_3=NULL
dataUruguay$psc1c2_4=NULL
dataUruguay$psc1c2_5=NULL
dataUruguay$psc1c2_6=NULL
dataUruguay$psc1c2_7=NULL
dataUruguay$psc1c2_8=NULL
dataUruguay$psc1c2_9=NULL
dataUruguay$psc1c2_10=NULL
dataUruguay$psc1c2_11=NULL
dataUruguay$psc1c2_12=NULL
dataUruguay$psc1c2_13=NULL
dataUruguay$psc1c2_14=NULL
dataUruguay$psc1c2_15=NULL
dataUruguay$psc1c2_16=NULL
dataUruguay$psc1c2_17=NULL
dataUruguay$psc1c2_18=NULL
dataUruguay$psc1c2_19=NULL
dataUruguay$psc1c2_77=NULL
dataUruguay$psc1c3=NULL
dataUruguay$psc1t1_1=NULL
dataUruguay$psc1t1_2=NULL
dataUruguay$psc1t1_3=NULL
dataUruguay$psc1t1_4=NULL
dataUruguay$psc1t1_5=NULL
dataUruguay$psc1t1_6=NULL
dataUruguay$psc1t1_77=NULL
dataUruguay$psc1c4=NULL
dataUruguay$psc1t2_1=NULL
dataUruguay$psc1t2_2=NULL
dataUruguay$psc1t2_2=NULL
dataUruguay$psc1t2_3=NULL
dataUruguay$psc1t2_4=NULL
dataUruguay$psc1t2_5=NULL
dataUruguay$psc1t2_6=NULL
dataUruguay$psc1t2_7=NULL
dataUruguay$psc1t2_8=NULL
dataUruguay$psc1t2_9=NULL
dataUruguay$psc1t2_10=NULL
dataUruguay$psc1t2_11=NULL
dataUruguay$psc1t2_12=NULL
dataUruguay$psc1t2_13=NULL
dataUruguay$psc1t2_14=NULL
dataUruguay$psc1t2_15=NULL
dataUruguay$psc1t2_16=NULL
dataUruguay$psc1t2_17=NULL
dataUruguay$psc1t2_18=NULL
dataUruguay$psc1t2_19=NULL
dataUruguay$psc1t2_77=NULL
dataUruguay$psc1t3=NULL
dataUruguay$psc1t4=NULL
dataUruguay$psc2n=NULL
dataUruguay$psc2r1=NULL
dataUruguay$psc2r2_1=NULL
dataUruguay$psc2r2_2=NULL
dataUruguay$psc2r2_3=NULL
dataUruguay$psc2r2_4=NULL
dataUruguay$psc2r2_5=NULL
dataUruguay$psc2r2_6=NULL
dataUruguay$psc2r2_7=NULL
dataUruguay$psc2r2_8=NULL
dataUruguay$psc2r2_9=NULL
dataUruguay$psc2r2_10=NULL
dataUruguay$psc2r2_11=NULL
dataUruguay$psc2r2_12=NULL
dataUruguay$psc2r2_13=NULL
dataUruguay$psc2r2_14=NULL
dataUruguay$psc2r2_15=NULL
dataUruguay$psc2r2_16=NULL
dataUruguay$psc2r2_17=NULL
dataUruguay$psc2r2_18=NULL
dataUruguay$psc2r2_19=NULL
dataUruguay$psc2r2_99=NULL
dataUruguay$psc2r2_77=NULL
dataUruguay$psc2c1=NULL
```
```{r}
dataUruguay$pr3enr=NULL
dataUruguay$drk1c=NULL
dataUruguay$drk1n=NULL
dataUruguay$drr1=NULL
dataUruguay$drr1a=NULL
dataUruguay$drr1b=NULL
dataUruguay$env1calt=NULL
dataUruguay$envp41=NULL
dataUruguay$envp42=NULL
dataUruguay$m1=NULL
dataUruguay$ing4=NULL
dataUruguay$exc2=NULL
dataUruguay$genor2=NULL
dataUruguay$genor4=NULL
dataUruguay$aojg2n=NULL
dataUruguay$aojg3n1=NULL
dataUruguay$mil10a=NULL
dataUruguay$mil10e=NULL
dataUruguay$ccch1=NULL
dataUruguay$ccch3=NULL
dataUruguay$ccch4=NULL
dataUruguay$ccch6=NULL
dataUruguay$ccus1=NULL
dataUruguay$ccus3=NULL
dataUruguay$ccus4=NULL
dataUruguay$ccus6=NULL
dataUruguay$ie1=NULL
dataUruguay$ie2=NULL
dataUruguay$edr=NULL
dataUruguay$ocup4a=NULL
dataUruguay$ocup4a=NULL
dataUruguay$q10newt=NULL
dataUruguay$q11n=NULL
dataUruguay$q12c=NULL
dataUruguay$q12bn=NULL
dataUruguay$covidedu1_1=NULL
dataUruguay$covidedu1_2=NULL
dataUruguay$covidedu1_3=NULL
```
```{r}
dataUruguay$jc13covid=NULL
dataUruguay$jc15a=NULL
dataUruguay$jccov1=NULL
dataUruguay$jccov2=NULL
dataUruguay$vic1ext=NULL
dataUruguay$aoj11=NULL
dataUruguay$countfair1=NULL
dataUruguay$countfair2=NULL
dataUruguay$countfair2=NULL
dataUruguay$countfair3=NULL
dataUruguay$countfair4=NULL
dataUruguay$wvsi3=NULL
dataUruguay$chm1bn=NULL
dataUruguay$chm2bn=NULL
dataUruguay$cses6n=NULL
dataUruguay$b0t=NULL
dataUruguay$b2=NULL
dataUruguay$b3=NULL
dataUruguay$b4=NULL
dataUruguay$b12=NULL
dataUruguay$b13=NULL
dataUruguay$b18=NULL
dataUruguay$b21=NULL
dataUruguay$b32=NULL
dataUruguay$b37=NULL
dataUruguay$b47a=NULL
dataUruguay$dst1bn=NULL
dataUruguay$pr3dnr=NULL
```
```{r}
dataUruguay$covidedu1_4=NULL
dataUruguay$covidedu1_5=NULL
dataUruguay$covidedu2=NULL
dataUruguay$etid=NULL
dataUruguay$gi0n=NULL
dataUruguay$r3=NULL
dataUruguay$r4=NULL
dataUruguay$r6=NULL
dataUruguay$r7=NULL
dataUruguay$r15=NULL
dataUruguay$r18n=NULL
dataUruguay$r18=NULL
dataUruguay$r16=NULL
dataUruguay$r27=NULL
dataUruguay$psc1n=NULL
dataUruguay$psc1c1=NULL
dataUruguay$psc1c2_1=NULL
dataUruguay$psc1c2_2=NULL
dataUruguay$psc1c2_3=NULL
dataUruguay$psc1c2_4=NULL
dataUruguay$psc1c2_5=NULL
dataUruguay$psc1c2_6=NULL
dataUruguay$psc1c2_7=NULL
dataUruguay$psc1c2_8=NULL
dataUruguay$psc1c2_9=NULL
dataUruguay$psc1c2_10=NULL
dataUruguay$psc1c2_11=NULL
dataUruguay$psc1c2_12=NULL
dataUruguay$psc1c2_13=NULL
dataUruguay$psc1c2_14=NULL
dataUruguay$psc1c2_15=NULL
dataUruguay$psc1c2_16=NULL
dataUruguay$psc1c2_17=NULL
dataUruguay$psc1c2_18=NULL
dataUruguay$psc1c2_19=NULL
dataUruguay$psc1c2_77=NULL
dataUruguay$psc1c3=NULL
dataUruguay$psc1t1_1=NULL
dataUruguay$psc1t1_2=NULL
dataUruguay$psc1t1_3=NULL
dataUruguay$psc1t1_4=NULL
dataUruguay$psc1t1_5=NULL
dataUruguay$psc1t1_6=NULL
dataUruguay$psc1t1_77=NULL
dataUruguay$psc1c4=NULL
dataUruguay$psc1t2_1=NULL
dataUruguay$psc1t2_2=NULL
dataUruguay$psc1t2_2=NULL
dataUruguay$psc1t2_3=NULL
dataUruguay$psc1t2_4=NULL
dataUruguay$psc1t2_5=NULL
dataUruguay$psc1t2_6=NULL
dataUruguay$psc1t2_7=NULL
dataUruguay$psc1t2_8=NULL
dataUruguay$psc1t2_9=NULL
dataUruguay$psc1t2_10=NULL
dataUruguay$psc1t2_11=NULL
dataUruguay$psc1t2_12=NULL
dataUruguay$psc1t2_13=NULL
dataUruguay$psc1t2_14=NULL
dataUruguay$psc1t2_15=NULL
dataUruguay$psc1t2_16=NULL
dataUruguay$psc1t2_17=NULL
dataUruguay$psc1t2_18=NULL
dataUruguay$psc1t2_19=NULL
dataUruguay$psc1t2_77=NULL
dataUruguay$psc1t3=NULL
dataUruguay$psc1t4=NULL
dataUruguay$psc2n=NULL
dataUruguay$psc2r1=NULL
dataUruguay$psc2r2_1=NULL
dataUruguay$psc2r2_2=NULL
dataUruguay$psc2r2_3=NULL
dataUruguay$psc2r2_4=NULL
dataUruguay$psc2r2_5=NULL
dataUruguay$psc2r2_6=NULL
dataUruguay$psc2r2_7=NULL
dataUruguay$psc2r2_8=NULL
dataUruguay$psc2r2_9=NULL
dataUruguay$psc2r2_10=NULL
dataUruguay$psc2r2_11=NULL
dataUruguay$psc2r2_12=NULL
dataUruguay$psc2r2_13=NULL
dataUruguay$psc2r2_14=NULL
dataUruguay$psc2r2_15=NULL
dataUruguay$psc2r2_16=NULL
dataUruguay$psc2r2_17=NULL
dataUruguay$psc2r2_18=NULL
dataUruguay$psc2r2_19=NULL
dataUruguay$psc2r2_99=NULL
dataUruguay$psc2r2_77=NULL
dataUruguay$psc2c1=NULL
```
```{r}
dataUruguay$psc2c2_1=NULL
dataUruguay$psc2c2_2=NULL
dataUruguay$psc2c2_3=NULL
dataUruguay$psc2c2_4=NULL
dataUruguay$psc2c2_5=NULL
dataUruguay$psc2c2_6=NULL
dataUruguay$psc2c2_7=NULL
dataUruguay$psc2c2_8=NULL
dataUruguay$psc2c2_9=NULL
dataUruguay$psc2c2_10=NULL
dataUruguay$psc2c2_11=NULL
dataUruguay$psc2c2_12=NULL
dataUruguay$psc2c2_13=NULL
dataUruguay$psc2c2_14=NULL
dataUruguay$psc2c2_15=NULL
dataUruguay$psc2c2_16=NULL
dataUruguay$psc2c2_17=NULL
dataUruguay$psc2c2_18=NULL
dataUruguay$psc2c2_19=NULL
dataUruguay$psc2c2_77=NULL
dataUruguay$psc2f1=NULL
dataUruguay$psc2f2_1=NULL
dataUruguay$psc2f2_2=NULL
dataUruguay$psc2f2_3=NULL
dataUruguay$psc2f2_4=NULL
dataUruguay$psc2f2_5=NULL
dataUruguay$psc2f2_6=NULL
dataUruguay$psc2f2_7=NULL
dataUruguay$psc2f2_8=NULL
dataUruguay$psc2f2_9=NULL
dataUruguay$psc2f2_10=NULL
dataUruguay$psc2f2_11=NULL
dataUruguay$psc2f2_12=NULL
dataUruguay$psc2f2_13=NULL
dataUruguay$psc2f2_14=NULL
dataUruguay$psc2f2_15=NULL
dataUruguay$psc2f2_16=NULL
dataUruguay$psc2f2_17=NULL
dataUruguay$psc2f2_18=NULL
dataUruguay$psc2f2_19=NULL
dataUruguay$psc2f2_77=NULL
dataUruguay$psc2f3=NULL
dataUruguay$psc2f4_1=NULL
dataUruguay$psc2f4_2=NULL
dataUruguay$psc2f4_3=NULL
dataUruguay$psc2f4_77=NULL
dataUruguay$psc7n=NULL
dataUruguay$psc8n=NULL
dataUruguay$psc9n=NULL
dataUruguay$psc14=NULL
dataUruguay$psc12n=NULL
```
```{r}
dataUruguay$psc11n=NULL
dataUruguay$psc11an=NULL
dataUruguay$psc15=NULL
dataUruguay$psc16=NULL
dataUruguay$psc13n_1=NULL
dataUruguay$psc13n_2=NULL
dataUruguay$psc13n_3=NULL
dataUruguay$psc13n_4=NULL
dataUruguay$psc13n_5=NULL
dataUruguay$psc13n_7=NULL
dataUruguay$psc13n_11=NULL
dataUruguay$psc13n_12=NULL
dataUruguay$psc13n_13=NULL
dataUruguay$psc13n_77=NULL
dataUruguay$idiomaq=NULL
dataUruguay$formatq=NULL
dataUruguay$sexi=NULL
dataUruguay$srvyrid=NULL
dataUruguay$fecha=NULL
dataUruguay$conocim=NULL
```
```{r}
dataUruguay$idnum=NULL
dataUruguay$uniq_id=NULL
dataUruguay$year=NULL
dataUruguay$wave=NULL
dataUruguay$estratopri=NULL
dataUruguay$nationality=NULL
dataUruguay$strata=NULL
dataUruguay$upm=NULL
dataUruguay$prov1t=NULL
```
```{r}
names(dataUruguay)
```
```{r}
dataUruguay$covid11f=NULL
dataUruguay$sd2new2=NULL
dataUruguay$sd3new2=NULL
dataUruguay$sd6new2=NULL
dataUruguay$sd5new2=NULL
dataUruguay$municipio1t=NULL
dataUruguay$ccch2=NULL
dataUruguay$ccch5=NULL
dataUruguay$ccus2=NULL
dataUruguay$ccus5=NULL
dataUruguay$psa27=NULL
dataUruguay$q14=NULL
dataUruguay$soc2acor=NULL
dataUruguay$soc2an1=NULL
dataUruguay$soc2an2=NULL
```
```{r}
names(dataUruguay)
```
cambiar nombre de variables
```{r}
names(dataUruguay) = c("Uruguay", "ParticipaciónU", "RespetoU", "ConfianzaU", "ToleranciaU", "TransparenciaU", "PercepciónU")
names(dataUruguay)
```
```{r}
datoscorru=merge(dataPerú,dataUruguay)
str(datoscorru)
```

